theme: jekyll-theme-minimal
title: Curriculum Vitae
logo: Bangkok-Property-Pace-2015-05-11_153154.jpg
description: Kankawee Chanasit's CV
name: Krawan
description: kankawee.ch@gmail.com
description: 0841094759
